# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QMainWindowDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 461)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/icon-tic-tac-toe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line_68 = QtWidgets.QFrame(self.centralwidget)
        self.line_68.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_68.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_68.setObjectName("line_68")
        self.gridLayout.addWidget(self.line_68, 4, 7, 1, 1)
        self.line_69 = QtWidgets.QFrame(self.centralwidget)
        self.line_69.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_69.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_69.setObjectName("line_69")
        self.gridLayout.addWidget(self.line_69, 6, 7, 1, 1)
        self.line_70 = QtWidgets.QFrame(self.centralwidget)
        self.line_70.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_70.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_70.setObjectName("line_70")
        self.gridLayout.addWidget(self.line_70, 2, 7, 1, 1)
        self.line_66 = QtWidgets.QFrame(self.centralwidget)
        self.line_66.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_66.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_66.setObjectName("line_66")
        self.gridLayout.addWidget(self.line_66, 6, 5, 1, 1)
        self.line_48 = QtWidgets.QFrame(self.centralwidget)
        self.line_48.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_48.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_48.setObjectName("line_48")
        self.gridLayout.addWidget(self.line_48, 4, 5, 1, 1)
        self.line_47 = QtWidgets.QFrame(self.centralwidget)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_47.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_47.setObjectName("line_47")
        self.gridLayout.addWidget(self.line_47, 2, 5, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 3, 1, 1)
        self.line_71 = QtWidgets.QFrame(self.centralwidget)
        self.line_71.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_71.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_71.setObjectName("line_71")
        self.gridLayout.addWidget(self.line_71, 4, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 3, 4, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 6, 3, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 3, 2, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setObjectName("line_13")
        self.gridLayout.addWidget(self.line_13, 2, 3, 1, 1)
        self.line_72 = QtWidgets.QFrame(self.centralwidget)
        self.line_72.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_72.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_72.setObjectName("line_72")
        self.gridLayout.addWidget(self.line_72, 2, 1, 1, 1)
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_9.sizePolicy().hasHeightForWidth())
        self.btn_9.setSizePolicy(sizePolicy)
        self.btn_9.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_9.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_9.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #c0c0c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.btn_9.setText("")
        self.btn_9.setIconSize(QtCore.QSize(60, 60))
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 2, 6, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6.sizePolicy().hasHeightForWidth())
        self.btn_6.setSizePolicy(sizePolicy)
        self.btn_6.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_6.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_6.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #c0c0c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.btn_6.setText("")
        self.btn_6.setIconSize(QtCore.QSize(60, 60))
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 4, 6, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8.sizePolicy().hasHeightForWidth())
        self.btn_8.setSizePolicy(sizePolicy)
        self.btn_8.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_8.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_8.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #c0c0c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.btn_8.setText("")
        self.btn_8.setIconSize(QtCore.QSize(60, 60))
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 2, 4, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2.sizePolicy().hasHeightForWidth())
        self.btn_2.setSizePolicy(sizePolicy)
        self.btn_2.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_2.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #c0c0c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.btn_2.setText("")
        self.btn_2.setIconSize(QtCore.QSize(60, 60))
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 6, 4, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3.sizePolicy().hasHeightForWidth())
        self.btn_3.setSizePolicy(sizePolicy)
        self.btn_3.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_3.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_3.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #c0c0c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.btn_3.setText("")
        self.btn_3.setIconSize(QtCore.QSize(60, 60))
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 6, 6, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4.sizePolicy().hasHeightForWidth())
        self.btn_4.setSizePolicy(sizePolicy)
        self.btn_4.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_4.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_4.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #c0c0c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.btn_4.setText("")
        self.btn_4.setIconSize(QtCore.QSize(60, 60))
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 4, 2, 1, 1)
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1.sizePolicy().hasHeightForWidth())
        self.btn_1.setSizePolicy(sizePolicy)
        self.btn_1.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_1.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_1.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #c0c0c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.btn_1.setText("")
        self.btn_1.setIconSize(QtCore.QSize(60, 60))
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 6, 2, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5.sizePolicy().hasHeightForWidth())
        self.btn_5.setSizePolicy(sizePolicy)
        self.btn_5.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_5.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_5.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #c0c0c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.btn_5.setText("")
        self.btn_5.setIconSize(QtCore.QSize(60, 60))
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 4, 4, 1, 1)
        self.line_45 = QtWidgets.QFrame(self.centralwidget)
        self.line_45.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_45.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_45.setObjectName("line_45")
        self.gridLayout.addWidget(self.line_45, 1, 4, 1, 1)
        self.line_46 = QtWidgets.QFrame(self.centralwidget)
        self.line_46.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_46.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_46.setObjectName("line_46")
        self.gridLayout.addWidget(self.line_46, 1, 6, 1, 1)
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7.sizePolicy().hasHeightForWidth())
        self.btn_7.setSizePolicy(sizePolicy)
        self.btn_7.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_7.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_7.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #c0c0c0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.btn_7.setText("")
        self.btn_7.setIconSize(QtCore.QSize(60, 60))
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 2, 2, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setObjectName("line_14")
        self.gridLayout.addWidget(self.line_14, 5, 4, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setObjectName("line_15")
        self.gridLayout.addWidget(self.line_15, 5, 2, 1, 1)
        self.line_29 = QtWidgets.QFrame(self.centralwidget)
        self.line_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setObjectName("line_29")
        self.gridLayout.addWidget(self.line_29, 7, 2, 1, 1)
        self.line_30 = QtWidgets.QFrame(self.centralwidget)
        self.line_30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setObjectName("line_30")
        self.gridLayout.addWidget(self.line_30, 1, 2, 1, 1)
        self.line_28 = QtWidgets.QFrame(self.centralwidget)
        self.line_28.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setObjectName("line_28")
        self.gridLayout.addWidget(self.line_28, 7, 4, 1, 1)
        self.line_27 = QtWidgets.QFrame(self.centralwidget)
        self.line_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setObjectName("line_27")
        self.gridLayout.addWidget(self.line_27, 7, 6, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setObjectName("line_16")
        self.gridLayout.addWidget(self.line_16, 5, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 8, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 3, 6, 1, 1)
        self.line_95 = QtWidgets.QFrame(self.centralwidget)
        self.line_95.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_95.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_95.setObjectName("line_95")
        self.gridLayout.addWidget(self.line_95, 6, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scene = QtWidgets.QGraphicsView(self.centralwidget)
        self.scene.setMinimumSize(QtCore.QSize(216, 100))
        self.scene.setMaximumSize(QtCore.QSize(16777215, 150))
        self.scene.setStyleSheet("")
        self.scene.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scene.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scene.setAlignment(QtCore.Qt.AlignCenter)
        self.scene.setObjectName("scene")
        self.verticalLayout_2.addWidget(self.scene)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scene_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.scene_2.setMinimumSize(QtCore.QSize(0, 30))
        self.scene_2.setMaximumSize(QtCore.QSize(70, 50))
        self.scene_2.setStyleSheet("")
        self.scene_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scene_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scene_2.setAlignment(QtCore.Qt.AlignCenter)
        self.scene_2.setObjectName("scene_2")
        self.horizontalLayout_2.addWidget(self.scene_2)
        self.scene_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.scene_4.setMinimumSize(QtCore.QSize(0, 30))
        self.scene_4.setMaximumSize(QtCore.QSize(50, 50))
        self.scene_4.setStyleSheet("")
        self.scene_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scene_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scene_4.setAlignment(QtCore.Qt.AlignCenter)
        self.scene_4.setObjectName("scene_4")
        self.horizontalLayout_2.addWidget(self.scene_4)
        self.lb_3_score = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_3_score.setFont(font)
        self.lb_3_score.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_3_score.setObjectName("lb_3_score")
        self.horizontalLayout_2.addWidget(self.lb_3_score)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scene_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.scene_3.setMinimumSize(QtCore.QSize(0, 30))
        self.scene_3.setMaximumSize(QtCore.QSize(70, 50))
        self.scene_3.setStyleSheet("")
        self.scene_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scene_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scene_3.setAlignment(QtCore.Qt.AlignCenter)
        self.scene_3.setObjectName("scene_3")
        self.horizontalLayout_3.addWidget(self.scene_3)
        self.scene_5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.scene_5.setMinimumSize(QtCore.QSize(0, 30))
        self.scene_5.setMaximumSize(QtCore.QSize(50, 50))
        self.scene_5.setStyleSheet("")
        self.scene_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scene_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scene_5.setAlignment(QtCore.Qt.AlignCenter)
        self.scene_5.setObjectName("scene_5")
        self.horizontalLayout_3.addWidget(self.scene_5)
        self.lb_4_score = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_4_score.setFont(font)
        self.lb_4_score.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_4_score.setObjectName("lb_4_score")
        self.horizontalLayout_3.addWidget(self.lb_4_score)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_4.addWidget(self.radioButton)
        spacerItem8 = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_5.addWidget(self.radioButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.radioButton_3.setAutoRepeat(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_6.addWidget(self.radioButton_3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_game_start = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_game_start.setFont(font)
        self.btn_game_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_game_start.setObjectName("btn_game_start")
        self.gridLayout_2.addWidget(self.btn_game_start, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Крестики-нолики"))
        self.lb_3_score.setText(_translate("MainWindow", "0 побед"))
        self.lb_4_score.setText(_translate("MainWindow", "0 побед"))
        self.label.setText(_translate("MainWindow", "Сложность"))
        self.radioButton.setText(_translate("MainWindow", "невозможно"))
        self.radioButton_2.setText(_translate("MainWindow", "сложно"))
        self.radioButton_3.setText(_translate("MainWindow", "легко"))
        self.pushButton.setText(_translate("MainWindow", "Сбросить счёт"))
        self.btn_game_start.setText(_translate("MainWindow", "Старт"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
